[build]
  # Esta es la ruta que ya corregiste en Netlify
  publish = "dist/mis-costillitas-admin/browser"

[[plugins]]
  # Este es el plugin problem√°tico
  package = "@netlify/angular-runtime"
  # Le decimos a Netlify que NO lo use
  disabled = true